// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8bw3erv-GwLcDWvfINf2KZ0oWXD19DSc',
    appId: '1:985414793635:android:5ed2790f9a356664a18216',
    messagingSenderId: '985414793635',
    projectId: 'firecartproductionapp',
    storageBucket: 'firecartproductionapp.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdYG9XtwVVwuwmTw2uih6p6d2O9895V2I',
    appId: '1:985414793635:web:5f1494b409e92c15a18216',
    messagingSenderId: '985414793635',
    projectId: 'firecartproductionapp',
    authDomain: 'firecartproductionapp.firebaseapp.com',
    storageBucket: 'firecartproductionapp.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdYG9XtwVVwuwmTw2uih6p6d2O9895V2I',
    appId: '1:985414793635:web:5f1494b409e92c15a18216',
    messagingSenderId: '985414793635',
    projectId: 'firecartproductionapp',
    authDomain: 'firecartproductionapp.firebaseapp.com',
    storageBucket: 'firecartproductionapp.appspot.com',
  );

}